services:
  - type: web
    name: binaire-freznel-assessment
    env: node
    plan: starter
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: CLIENT_URL
        value: https://binaire-freznel-assessment-ebon.vercel.app,http://localhost:5173
      - key: WORKER_POOL_SIZE
        value: 4
      - key: TASK_TIMEOUT_MS
        value: 30000
